# Generated by Django 3.2.19 on 2023-06-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20230628_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='otp_verified',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='otp_auth_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='otp_base32',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
