# Generated by Django 3.2.19 on 2023-07-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
